spring:
  application:
    name: users
  datasource:
    url: jdbc:postgresql://${USERS.DB.URL}:5432/users
    username: ${USERS.DB.USERNAME}
    password: ${USERS.DB.PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/users-changelog.xml
token:
  signing:
    key: ${JWT.SECRET}
logging:
  level:
    org:
      springframework:
        security: DEBUG
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: http://localhost:5454/swagger-ui/index.html



