name: CI/CD with Docker Registry

on:
  push:
    branches:
      - master  # Запуск при пуше в master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Установить JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Установить права на выполнение gradlew
        run: chmod +x ./gradlew

      - name: run docker
        run: |
          ./gradlew jib --image=feral.servebeer.com:5000/users:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Деплой на сервер через SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/opt/translate
            docker stop $(docker ps -q --filter "ancestor=feral.servebeer.com:5000/users:latest")
            docker system prune -af
            docker-compose pull
            docker-compose up -d --force-recreate
