name: CI/CD with Docker Registry

on:
  push:
    branches:
      - master  # Запуск при пуше в master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Установить JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Установить права на выполнение gradlew
        run: chmod +x ./gradlew

      - name: run docker
        run: |
          ./gradlew :bootBuildImage 
          ./gradlew :pushImage
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Деплой на сервер через SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/opt/translate
            docker login 127.0.0.1:5000 -u feral -p 8925
            # Загружаем Docker образ
            # docker load -i users.tar

            # Тегируем образ для локального реестра
            docker tag users:latest 127.0.0.1:5000/users:latest

            # Отправляем образ в локальный реестр
            # docker push 127.0.0.1:5000/users:latest

            # Обновляем контейнеры с использованием docker-compose
            docker-compose down  # Останавливаем старые контейнеры
            docker-compose up -d --force-recreate  # Перезапускаем контейнеры с новыми образами

            # Очищаем неиспользуемые образы и контейнеры
            docker system prune -af

